export 'presentation/components/activity_section.dart';
export 'presentation/components/bill_board.dart';
export 'presentation/components/home_app_bar.dart';
export 'presentation/components/recommendation_section.dart';
export 'package:flutter_svg/svg.dart';
export 'presentation/views/home_view.dart';
export 'presentation/widgets/activity_box.dart';
export 'presentation/widgets/recommendation_box.dart';
export 'presentation/widgets/see_all_tile.dart';
