// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctpTnKE1vvn2uEH6zQf80-9byZKTG2h0',
    appId: '1:19827522913:android:2bcbaace2ea50aed395920',
    messagingSenderId: '19827522913',
    projectId: 'skeen-fd7c8',
    storageBucket: 'skeen-fd7c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZYa6ic0qniPPDlopePIxQf_Zd1zsdUs',
    appId: '1:19827522913:ios:822cf2753022fcb6395920',
    messagingSenderId: '19827522913',
    projectId: 'skeen-fd7c8',
    storageBucket: 'skeen-fd7c8.appspot.com',
    androidClientId: '19827522913-qj2t084a1husn9d9piuj1ce9d70v2674.apps.googleusercontent.com',
    iosClientId: '19827522913-pqso9avo70bpalnse8fi5dc415u2p0pa.apps.googleusercontent.com',
    iosBundleId: 'com.skeen.hack',
  );

}